name: polkadot
title: Polkadot
base: core22
adopt-info: polkadot
summary: Polkadot - A multi-chain framework for better blockchain interoperability
license: GPL-3.0-with-GCC-exception
contact: info@dwellir.com
issues: https://github.com/dwellir-public/snap-polkadot/issues
source-code: https://github.com/dwellir-public/snap-polkadot/
website: https://www.dwellir.com
grade: stable
confinement: strict

architectures:
  - amd64

description: |
  Polkadot is a multi-chain framework that enables interoperability and scalability for multiple blockchains.
  See: https://github.com/paritytech/polkadot-sdk
  
  Hardware requirements can be found here: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#standard-hardware

  Start the service with 'sudo snap start polkadot'

  Check logs from the Polkadot service with 'snap logs polkadot -f'

  Supported configuration options for the snap:
  
  service-args [default=--base-path=$SNAP_COMMON/polkadot_base --name=<hostname>]
  For available arguments see https://github.com/paritytech/polkadot-sdk
  The value set here will be passed to the Polkadot binary with a few exceptions listed below. 
  * --name defaults to the systems hostname the first time the snap is installed.
  * --base-path is always set by the snap to `$SNAP_COMMON/polkadot_base` and is not allowed to be configured.

  endure [default=false]
  If true the Polkadot service will not be restarted after a snap refresh.
  Note that the Polkadot service will still be restarted as the result of changing service-args, etc.

  Use this when restarts should be avoided e.g. when running a validator.

parts:

  rust-deps:
    plugin: nil
    build-packages:
     - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      rustup default stable
      rustup update
      rustup target add wasm32-unknown-unknown
      rustup component add rust-src
      rustup update nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup component add rust-src --toolchain nightly

  polkadot:
    after: [rust-deps]
    plugin: rust
    source: https://github.com/paritytech/polkadot-sdk.git
    source-tag: polkadot-v1.10.0
    source-depth: 1
    build-packages:
      - build-essential
      - libssl-dev
      - git 
      - clang 
      - libclang-dev 
      - pkg-config
      - protobuf-compiler
    # Make the commit hash available for snap info
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --abbrev=10)-$(git rev-parse --short HEAD)"
    rust-path:
      - polkadot/
    prime:
      - bin/polkadot
      - bin/polkadot-execute-worker
      - bin/polkadot-prepare-worker

  wrappers:
    plugin: dump
    source-type: local
    source: .
    stage:
      - wrappers/
  
  utils:
      plugin: dump
      source-type: local
      source: .
      stage:
        - utils/

apps:
  polkadot:
    command: wrappers/start-polkadot.bash
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: never
    plugs:
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
