name: Build and publish Polkadot snap

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
    - name: Save snapcraft log
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: ${{ failure() && steps.snapcraft.conclusion == 'failure' }}
      with:
        name: log
        path: /home/runner/.local/state/snapcraft/log/snapcraft-*.log
  # test:
  #   runs-on: ubuntu-latest
  # publish:
  #   runs-on: ubuntu-latest
